---
- name: Create AWS Infrastructure and Instances
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Create a VPC
      amazon.aws.ec2_vpc_net:
        name: "ansible-vpc"
        cidr_block: "10.0.0.0/16"
        dns_support: true
        dns_hostnames: true
        region: "ap-southeast-1"  # Corrected region
        state: present
      register: vpc
      
    - name: Create a Subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "10.0.1.0/24"
        az: "ap-southeast-1a"
        region: "ap-southeast-1"
        state: present
        tags:
          Name: "Ansible_subnet"
      register: subnet
  
    - name: Create an Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "ap-southeast-1"
        state: present
      register: igw

    - name: Get the Default Route Table
      amazon.aws.ec2_vpc_route_table_info:
        region: "ap-southeast-1"
        filters:
          vpc-id: "{{ vpc.vpc.id }}"
      register: route_table_info

    - name: Add Route to Internet Gateway
      amazon.aws.ec2_vpc_route_table:
        route_table_id: "{{ route_table_info.route_tables[0].id }}"
        region: "ap-southeast-1"
        routes:
          routes:
          - destination_cidr_block: "0.0.0.0/0"
            gateway_id: "{{ igw.internet_gateway_id }}"
        state: present

    - name: Create a Security Group
      amazon.aws.ec2_security_group:
        name: "ansible-security-group"
        description: "Security group for Ubuntu instances"
        vpc_id: "{{ vpc.vpc.id }}"
        region: "ap-southeast-1"
        state: present
      register: sg

    - name: Add Ingress Rules to Security Group
      amazon.aws.ec2_security_group:
        security_group_id: "{{ sg.group_id }}"
        region: "ap-southeast-1"
        rules:
          - proto: tcp
            ports:
              - 80
              - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: "Allow HTTP traffic"
        state: present

    - name: Fetch Ubuntu 20.04 AMI ID
      amazon.aws.ec2_ami_info:
        region: "ap-southeast-1"
        filters:
          name: "ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*"
      register: ami_info

    - name: Launch 3 EC2 Instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        key_name: "ansible-key"
        instance_type: "t2.micro"
        image_id: "{{ ami_info.images[0].image_id }}"
        region: "ap-southeast-1"
        vpc_subnet_id: "{{ subnet.subnet.id }}"   # Ensure this variable is defined
        security_group: "{{ sg.group_id }}"       # Ensure this variable is defined
      loop:
        - ansible-instance-1
        - ansible-instance-2
        - ansible-instance-3
      register: ec2

    - name: Display Instance Details
      debug:
        var: ec2.instances
